{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "yasp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yasp.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "yasp.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: http
          protocol: TCP
    {{- with .Values.networkPolicy.ingress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - ports:
        - port: 5432
          protocol: TCP
    - ports:
        - port: 25
          protocol: TCP
        - port: 465
          protocol: TCP
        - port: 587
          protocol: TCP
    - ports:
        - port: 443
          protocol: TCP
    {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
