/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'service-groups': ServiceGroup;
    services: Service;
    incidents: Incident;
    maintenances: Maintenance;
    notifications: Notification;
    subscribers: Subscriber;
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'service-groups': ServiceGroupsSelect<false> | ServiceGroupsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    incidents: IncidentsSelect<false> | IncidentsSelect<true>;
    maintenances: MaintenancesSelect<false> | MaintenancesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    'email-settings': EmailSetting;
    'sms-settings': SmsSetting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'email-settings': EmailSettingsSelect<false> | EmailSettingsSelect<true>;
    'sms-settings': SmsSettingsSelect<false> | SmsSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      sendNotificationFromCollection: TaskSendNotificationFromCollection;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-groups".
 */
export interface ServiceGroup {
  id: number;
  _order?: string | null;
  name: string;
  /**
   * URL-friendly identifier (e.g., "core-infrastructure")
   */
  slug: string;
  /**
   * Optional description for this service group
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  _order?: string | null;
  name: string;
  /**
   * URL-friendly identifier (e.g., "api-gateway")
   */
  slug: string;
  /**
   * Optional description for this service
   */
  description?: string | null;
  /**
   * Which group this service belongs to
   */
  group: number | ServiceGroup;
  /**
   * Current status of the service
   */
  status: 'operational' | 'degraded' | 'partial' | 'major' | 'maintenance';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incidents".
 */
export interface Incident {
  id: number;
  /**
   * A brief description of the incident (e.g., "API Gateway Latency Issues")
   */
  title: string;
  /**
   * Auto-generated short ID for permalinks
   */
  shortId?: string | null;
  /**
   * Automatically synced from the latest update
   */
  status: 'investigating' | 'identified' | 'monitoring' | 'resolved';
  /**
   * When the incident was resolved
   */
  resolvedAt?: string | null;
  /**
   * Services affected by this incident
   */
  affectedServices?: (number | Service)[] | null;
  /**
   * Timeline of updates for this incident. At least one update is required.
   */
  updates: {
    /**
     * Status at the time of this update
     */
    status: 'investigating' | 'identified' | 'monitoring' | 'resolved';
    /**
     * Update message
     */
    message: string;
    /**
     * When this update was posted
     */
    createdAt: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenances".
 */
export interface Maintenance {
  id: number;
  /**
   * A brief description of the maintenance (e.g., "Database Migration")
   */
  title: string;
  /**
   * Auto-generated short ID for permalinks
   */
  shortId?: string | null;
  /**
   * Detailed description of the maintenance work
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Services that will be affected by this maintenance
   */
  affectedServices?: (number | Service)[] | null;
  /**
   * When the maintenance is scheduled to start
   */
  scheduledStartAt: string;
  /**
   * When the maintenance is expected to end
   */
  scheduledEndAt?: string | null;
  /**
   * Human-readable duration (e.g., "~2 hours")
   */
  duration?: string | null;
  /**
   * Current status of the maintenance
   */
  status: 'upcoming' | 'in_progress' | 'completed' | 'cancelled';
  /**
   * Automatically set to "In Progress" when start time is reached
   */
  autoStartOnSchedule?: boolean | null;
  /**
   * Automatically set to "Completed" when end time is reached
   */
  autoCompleteOnSchedule?: boolean | null;
  /**
   * Optional timeline of updates for this maintenance
   */
  updates?:
    | {
        /**
         * Status at the time of this update
         */
        status: 'upcoming' | 'in_progress' | 'completed' | 'cancelled';
        /**
         * Update message
         */
        message: string;
        /**
         * When this update was posted
         */
        createdAt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage and send notifications to subscribers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  /**
   * Internal title for this notification (auto-generated)
   */
  title: string;
  relatedIncident?: (number | null) | Incident;
  relatedMaintenance?: (number | null) | Maintenance;
  updateIndex?: number | null;
  channel: 'email' | 'sms' | 'both';
  status: 'draft' | 'scheduled' | 'sent' | 'failed';
  /**
   * Subject line for email notifications
   */
  subject?: string | null;
  /**
   * Full email message content. Use {{siteUrl}} for the site URL.
   */
  emailBody?: string | null;
  /**
   * Short SMS message (160 characters recommended)
   */
  smsBody?: string | null;
  recipientCount?: number | null;
  errorMessage?: string | null;
  sentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  /**
   * Type of subscription
   */
  type: 'email' | 'sms';
  /**
   * Required if subscription type is email
   */
  email?: string | null;
  /**
   * Required if subscription type is SMS (include country code)
   */
  phone?: string | null;
  /**
   * Whether the subscription has been verified
   */
  verified?: boolean | null;
  /**
   * Token used for email/phone verification
   */
  verificationToken?: string | null;
  /**
   * Token used for one-click unsubscribe
   */
  unsubscribeToken?: string | null;
  /**
   * Whether the subscription is active
   */
  active?: boolean | null;
  /**
   * IP address used when subscribing (for rate limiting)
   */
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * User role for access control
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for accessibility
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'sendNotificationFromCollection';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'sendNotificationFromCollection') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'service-groups';
        value: number | ServiceGroup;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'incidents';
        value: number | Incident;
      } | null)
    | ({
        relationTo: 'maintenances';
        value: number | Maintenance;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-groups_select".
 */
export interface ServiceGroupsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  slug?: T;
  description?: T;
  group?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incidents_select".
 */
export interface IncidentsSelect<T extends boolean = true> {
  title?: T;
  shortId?: T;
  status?: T;
  resolvedAt?: T;
  affectedServices?: T;
  updates?:
    | T
    | {
        status?: T;
        message?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenances_select".
 */
export interface MaintenancesSelect<T extends boolean = true> {
  title?: T;
  shortId?: T;
  description?: T;
  affectedServices?: T;
  scheduledStartAt?: T;
  scheduledEndAt?: T;
  duration?: T;
  status?: T;
  autoStartOnSchedule?: T;
  autoCompleteOnSchedule?: T;
  updates?:
    | T
    | {
        status?: T;
        message?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  title?: T;
  relatedIncident?: T;
  relatedMaintenance?: T;
  updateIndex?: T;
  channel?: T;
  status?: T;
  subject?: T;
  emailBody?: T;
  smsBody?: T;
  recipientCount?: T;
  errorMessage?: T;
  sentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  type?: T;
  email?: T;
  phone?: T;
  verified?: T;
  verificationToken?: T;
  unsubscribeToken?: T;
  active?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * The name of your organization/site
   */
  siteName: string;
  /**
   * A brief description of your status page
   */
  siteDescription?: string | null;
  /**
   * Text displayed in the footer. Supports bold, italic, underline, and links. Leave empty for default.
   */
  footerText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Title shown in browser tabs and search results (leave empty to use Site Name)
   */
  metaTitle?: string | null;
  /**
   * Description shown in search results
   */
  metaDescription?: string | null;
  /**
   * Title for the incident history page (use {{date}} for dynamic date)
   */
  historyMetaTitle?: string | null;
  /**
   * Description for the incident history page (use {{date}} for dynamic date)
   */
  historyMetaDescription?: string | null;
  /**
   * Site favicon (recommended: 32x32 or 64x64 PNG, ICO, or SVG). Leave empty to use default favicon.
   */
  favicon?: (number | null) | Media;
  /**
   * Logo to display on light backgrounds (recommended: SVG or PNG with transparent background)
   */
  logoLight?: (number | null) | Media;
  /**
   * Logo to display on dark backgrounds (recommended: SVG or PNG with transparent background)
   */
  logoDark?: (number | null) | Media;
  /**
   * Force display of maintenance banner regardless of service status
   */
  maintenanceModeEnabled?: boolean | null;
  /**
   * Override the default status banner message (leave empty to use automatic)
   */
  customStatusMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-settings".
 */
export interface EmailSetting {
  id: number;
  /**
   * Allow users to subscribe via email (requires SMTP to be configured)
   */
  enabled?: boolean | null;
  /**
   * SMTP server hostname (e.g., smtp.gmail.com, smtp.sendgrid.net)
   */
  smtpHost?: string | null;
  /**
   * SMTP port (typically 587 for TLS, 465 for SSL, 25 for unencrypted)
   */
  smtpPort?: number | null;
  /**
   * Connection security method
   */
  smtpSecure?: ('tls' | 'ssl' | 'none') | null;
  /**
   * Username for SMTP authentication (often your email address)
   */
  smtpUsername?: string | null;
  /**
   * Password or API key for SMTP authentication. Leave empty to keep existing value.
   */
  smtpPassword?: string | null;
  /**
   * Email address that notifications will be sent from
   */
  smtpFromAddress?: string | null;
  /**
   * Display name for the sender (e.g., "Acme Status")
   */
  smtpFromName?: string | null;
  /**
   * Optional reply-to email address (leave empty to use From address)
   */
  smtpReplyTo?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sms-settings".
 */
export interface SmsSetting {
  id: number;
  /**
   * Allow users to subscribe via SMS (requires Twilio to be configured)
   */
  enabled?: boolean | null;
  /**
   * Your Twilio Account SID (starts with AC...)
   */
  twilioAccountSid?: string | null;
  /**
   * Your Twilio Auth Token. Leave empty to keep existing value.
   */
  twilioAuthToken?: string | null;
  /**
   * Your Twilio phone number (e.g., +1234567890). Required if not using a Messaging Service.
   */
  twilioFromNumber?: string | null;
  /**
   * Use a Messaging Service instead of a phone number for better deliverability. Required if not using a From Phone Number.
   */
  twilioMessagingServiceSid?: string | null;
  /**
   * Maximum characters for {{title}} placeholder. Longer titles will be truncated.
   */
  templateTitleMaxLength?: number | null;
  /**
   * Maximum characters for {{message}} placeholder. Longer messages will be truncated.
   */
  templateMessageMaxLength?: number | null;
  /**
   * Template for new incident notifications
   */
  templateIncidentNew?: string | null;
  /**
   * Template for incident update notifications
   */
  templateIncidentUpdate?: string | null;
  /**
   * Template for new scheduled maintenance notifications. {{schedule}} includes start/end times.
   */
  templateMaintenanceNew?: string | null;
  /**
   * Template for maintenance update notifications
   */
  templateMaintenanceUpdate?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  footerText?: T;
  metaTitle?: T;
  metaDescription?: T;
  historyMetaTitle?: T;
  historyMetaDescription?: T;
  favicon?: T;
  logoLight?: T;
  logoDark?: T;
  maintenanceModeEnabled?: T;
  customStatusMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-settings_select".
 */
export interface EmailSettingsSelect<T extends boolean = true> {
  enabled?: T;
  smtpHost?: T;
  smtpPort?: T;
  smtpSecure?: T;
  smtpUsername?: T;
  smtpPassword?: T;
  smtpFromAddress?: T;
  smtpFromName?: T;
  smtpReplyTo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sms-settings_select".
 */
export interface SmsSettingsSelect<T extends boolean = true> {
  enabled?: T;
  twilioAccountSid?: T;
  twilioAuthToken?: T;
  twilioFromNumber?: T;
  twilioMessagingServiceSid?: T;
  templateTitleMaxLength?: T;
  templateMessageMaxLength?: T;
  templateIncidentNew?: T;
  templateIncidentUpdate?: T;
  templateMaintenanceNew?: T;
  templateMaintenanceUpdate?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendNotificationFromCollection".
 */
export interface TaskSendNotificationFromCollection {
  input: {
    notificationId: string;
    channel: string;
    subject?: string | null;
    emailBody?: string | null;
    smsBody?: string | null;
    itemTitle: string;
    itemUrl: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}